export const YOUTUBE_LOGO = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/YouTube_Logo_2017.svg/2560px-YouTube_Logo_2017.svg.png"
export const HAMBURGER_ICON = "https://icon-library.com/images/hamburger-menu-icon-png-white/hamburger-menu-icon-png-white-13.jpg"
export const USER_ICON = "https://www.iconpacks.net/icons/2/free-user-icon-3296-thumb.png"
export const SEARCH_ICON = "https://www.iconpacks.net/icons/2/free-search-icon-2903-thumb.png"
export const HOME_ICON = "https://pixlok.com/wp-content/uploads/2021/12/Instagram-Home-Icon-n3fd2.png"
export const SHORTS_ICON = "https://www.iconpacks.net/icons/5/free-youtube-shorts-logo-icon-15252-thumb.png"
export const SUBSCRIPTION_ICON = "https://cdn-icons-png.flaticon.com/512/1077/1077046.png"
export const LIBRARY_ICON = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtj3B15Jblbn6QkLKop-RY8tUqhp7lqp-6ng&usqp=CAU"
export const HISTORY_ICON = "https://uxwing.com/wp-content/themes/uxwing/download/computers-mobile-hardware/history-icon.png"
export const YOUR_VIDEO_ICON = "https://icon-library.com/images/youtube-video-icon-png/youtube-video-icon-png-27.jpg"
export const WATCH_LATER_ICON = "https://cdn.iconscout.com/icon/free/png-256/watch-later-1781603-1513853.png"
export const LIKE_ICON = "https://icon-library.com/images/like-icon-youtube/like-icon-youtube-27.jpg"
export const DISLIKE_ICON = "https://icons-for-free.com/download-icon-bx+dislike-1325051870513186092_512.png"
export const AFTER_LIKE_ICON = "https://www.freeiconspng.com/uploads/youtube-like-button-png-11.png"
export const AFTER_DISLIKE_ICON = "https://www.freeiconspng.com/thumbs/youtube-dislike-png/black-and-white-youtube-dislike-21.png"

const YOUTUBE_API_KEY = "AIzaSyDdl3k-EZ3W_NPtkQZ5aLSrVFNbTQnqvtM"
export const YOUTUBE_POPULAR_VIDEO_LIST = "https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&regionCode=IN&maxResults=50&key="+YOUTUBE_API_KEY
export const YOUTUBE_SEARCH_API = "https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=4&key="+YOUTUBE_API_KEY+"&q="
export const YOUTUBE_RELATED_API = "https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&key="+YOUTUBE_API_KEY+"&relatedToVideoId="
export const YOUTUBE_VIDEO_INFO = "https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&key="+YOUTUBE_API_KEY+"&id="
export const YOUTUBE_SEARCH_AUTOSUGGEST = "http://suggestqueries.google.com/complete/search?client=firefox&ds=yt&q="
export const YOUTUBE_VIDEO_COMMENT = "https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet%2Creplies&key="+YOUTUBE_API_KEY+"&videoId="
export const YOUTUBE_SEARCH_VIDEOS_LIST = "https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&key="+YOUTUBE_API_KEY+"&id="